apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: master01:5000/demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_SERVICE_HOST
          value: loginregistermysql
        - name: MYSQL_SERVICE_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: root
          